import "@/app/globals.css";
import logo from "@/public/logo.png";
import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,

  display: "swap",
});

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["200", "400", "700"],
  variable: "--font-ibm-plex-sans-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Cairo Institute of Liberal Arts and Sciences",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${ibmPlexSansArabic.variable} min-w-screen mx-10 mt-10`}
      >
        <header className="mb-20 flex flex-col items-center justify-between gap-5 md:flex-row md:gap-10">
          <div
            
            className="flex h-auto flex-col items-center gap-5 md:flex-row"
            >
              <Link href="/" >
            <Image
              src={logo}
              width={25}
              alt="Cairo Institute of Liberal Arts and Sciences"
            />
            </Link>
            <Link href="/" >
            <h1 className="text-center font-bold md:text-left">
              Cairo Institute of Liberal Arts and Sciences
            </h1>
            </Link>
          </div>
   
        </header>

        {children}
      </body>
    </html>
  );
}
