import { validateRequest } from "@/app/(Auth)/_lib/auth.lucia";
import { MobileHeader } from "@/app/(dashboard)/_components/layout/mobile.header";
import { LayoutSidebar } from "@/app/(dashboard)/_components/layout/sidebar";
import "@/app/globals.css";
import { RootProvider } from "@/lib/providers";
import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { LayoutBreadcrumb } from "../_components/layout/breadcrumb";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,
  display: "swap",
});
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["200", "400", "700"],
  variable: "--font-ibm-plex-sans-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();

  if (!user || user.role !== "admin") {
    return redirect("/signin");
  }

  return (
    <html lang="en" suppressHydrationWarning className="max-h-screen overflow-hidden">
      <body
        className={`${inter.variable} ${ibmPlexSansArabic.variable} bg-background max-w-screen leading-relaxed text-pretty antialiased`}
        id="dashboard"
      >
        <RootProvider>
          <MobileHeader />
          <div className="flex">
            <LayoutSidebar className="h-screen border-r pt-5" />
            <main className="flex max-h-screen flex-1 flex-col overflow-x-hidden overflow-y-auto">
              <LayoutBreadcrumb />
              {children}
            </main>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
