import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Inter } from "next/font/google";

import "@/app/globals.css";

import { ThemeProvider } from "@/lib/providers/theme.provider";

import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,
  display: "swap",
});
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["200", "400", "700"],
  variable: "--font-ibm-plex-sans-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

import { LayoutSidebar } from "@/app/(dashboard)/_components/layout/sidebar";
import { validateRequest } from "@/lib/apis/auth.api";
import { RootProvider } from "@/lib/providers";
import { redirect } from "next/navigation";
import { LayoutBreadcrumb } from "../_components/layout/breadcrumb";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();

  if (!user || user.role !== "admin") {
    return redirect("/signin");
  }

  return (
    <RootProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} ${ibmPlexSansArabic.variable} bg-background max-w-screen leading-relaxed text-pretty antialiased`}
          id="dashboard"
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster richColors />
            <div className="flex h-screen overflow-hidden">
              <LayoutSidebar className="h-screen border-r pt-5" />
              {/* <LayoutHeader className="z-40 h-16 px-5 sm:pl-0" /> */}
              <main className="max-h-screen flex-1 overflow-x-hidden overflow-y-auto">
                <LayoutBreadcrumb />
                {children}
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </RootProvider>
  );
}
