import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Amiri } from "next/font/google";

import "@/app/globals.css";

import LayoutSidebar from "@/components/dashboard/LayoutSidebar";
import LayoutHeader from "@/components/dashboard/LayoutHeader";
import LayoutBreadcrumb from "@/components/dashboard/LayoutBreadcrumb";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,
  display: "swap",
});
const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-amiri",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${amiri.variable} `}>
        <Toaster richColors />
        <main>
          <LayoutSidebar />
          <LayoutHeader>{children}</LayoutHeader>
        </main>
      </body>
    </html>
  );
}
