import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";

import "@/app/globals.css";

import LayoutSidebar from "@/components/dashboard/LayoutSidebar";
import LayoutHeader from "@/components/dashboard/LayoutHeader";
import { ThemeProvider } from "@/providers/Theme.provider";
import { CourseProvider } from "@/providers/Courses.provider";
import { getArchivedCourses, getDraftCourses } from "@/actions/courses.actions";

import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,
  display: "swap",
});
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "800"],
  variable: "--font-cairo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

import { validateRequest } from "@/lib/auth";
import { redirect } from "next/navigation";
import { CourseType } from "@/providers/CourseState.provider";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();
  if (!user) {
    return redirect("/signin");
  }

  const archivedCourses = (await getArchivedCourses()) as CourseType[];
  const draftCourses = (await getDraftCourses()) as CourseType[];

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${cairo.variable} max-w-screen scroll-smooth`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CourseProvider
            currentCourses={[]}
            draftCourses={draftCourses}
            archivedCourses={archivedCourses}
          >
            <Toaster richColors />
            <main>
              <LayoutSidebar />
              <LayoutHeader>{children}</LayoutHeader>
            </main>
          </CourseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
